# Generated by Django 2.2.5 on 2019-09-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190907_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=120)),
                ('retype_password', models.CharField(max_length=120)),
            ],
        ),
    ]
