# Generated by Django 2.2.5 on 2019-09-10 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190909_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 10, 8, 34, 10, 700939), verbose_name='date published'),
        ),
    ]
